name: golangci-lint
on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.54.0
          sudo mv ./golangci-lint /usr/local/bin/golangci-lint
          golangci-lint --version

      - name: Run golangci-lint
        run: golangci-lint run --timeout 5m
